sudo: required
services:
  - docker

before_install:
  - docker build -t jamessutterfield/react-text -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jamessutterfield/react-test npm test

after_success:
  - docker build -t jamessutterfield/multi-client ./client
  - docker build -t jamessutterfield/multi-nginx ./nginx
  - docker build -t jamessutterfield/multi-server ./server
  - docker build -t jamessutterfield/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jamessutterfield/multi-client
  - docker push jamessutterfield/multi-nginx
  - docker push jamessutterfield/multi-server
  - docker push jamessutterfield/multi-worker
